server:
  port: ${CohenServerPort}
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql:///${CohenDatabaseName}?serverTimezone=${CohenTimeZone}&characterEncoding=UTF-8
    username: ${CohenDatabaseUsername}
    password: ${CohenDatabasePassword}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  level:
    root: trace
  file:
    path: ${CohenLoggingFilePath}