version: "3.7"

services:
  cohen:
    build:
      dockerfile: ./DockerTests/Dockerfile
      context: ../
    networks:
      - cohen-net-test
    depends_on:
      - db
    volumes:
      - ~/.m2:/root/.m2

  db:
    build:
      dockerfile: ./DockerTests/DockerfileMysql
      context: ../
    volumes:
      - ~/cohen/db-data:/var/lib/mysql
    networks:
      - cohen-net-test
    environment:
      MYSQL_ROOT_PASSWORD: ASD2100150

networks:
  cohen-net-test: