name: CI

on:
  push:
    branches:
      - master

jobs:
  test-deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      #     - name: run test docker-compose.yml
      #       run: docker-compose -f DockerTests/docker-compose.yml run cohen
      - name: copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "."
          rm: true
          target: "/root/java/cohen"
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
                    source ~/.profile
                    cd /root/java/cohen
                    docker-compose stop
                    docker build -f DockerfileMysql -t cohen-mysql:latest .
                    docker run --name cohen-mysql -v ~/cohen/db-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=ASD2100150 -d cohen-mysql:latest
#                        read -p "Pause Time 5 seconds" -t 5
                    sleep 5
                    docker exec -i cohen-mysql sh -c 'exec mysql -uroot -pASD2100150' < sql/update.sql
                    docker stop cohen-mysql
                    docker container rm cohen-mysql
                    docker-compose -f DockerTests/docker-compose.yml build
                    docker-compose -f DockerTests/docker-compose.yml run cohen
                    docker-compose -f DockerTests/docker-compose.yml stop
                    docker-compose build
                    docker-compose up --force-recreate -d
