name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: run test docker-compose.yml
      run: docker-compose -f DockerTests/docker-compose.yml run cohen
      
  deploy:
    
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        rm: true
        target: "/root/cohen"
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/cohen
          docker-compose up --build
        
