name: CI

on:
  push:
    branches: 
    - master

jobs:
  test-deploy:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
#     - name: run test docker-compose.yml
#       run: docker-compose -f DockerTests/docker-compose.yml run cohen
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "."
        rm: true
        target: "/root/cohen"
    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd /root/cohen
          docker-compose -f DockerTests/docker-compose.yml build --no-cache
          docker-compose -f DockerTests/docker-compose.yml run cohen
          docker-compose build --no-cache
          docker-compose stop
          docker-compose up --force-recreate -d
                
